Squasheddaeobjexport
Markemp/Cryengine-Converter pull request #107
Opened 2021-09-22 12:39 UTC by lonelyhawk

exporting both .dae and .obj files simultaneously squashed the model
![image](https://user-images.githubusercontent.com/16024236/134344806-51840aa5-5ba8-4cd4-b7e7-4dba90cf911d.png)
![image](https://user-images.githubusercontent.com/16024236/134344927-361450be-d397-4d27-83bb-2bfc0d07aab0.png)

2021-09-23 21:22 UTC, Kjasi commented
Looks good to me!

2021-09-25 15:17 UTC, Markemp requested changes
Just 2 small code cleanup items.  Thank you!

2021-09-25 15:17 UTC, Markemp commented on CgfConverter/Renderers/Wavefront/Wavefront.cs
> +                            //file.WriteLine("o {0}", node.Name);
Can you delete unneeded code & comments?

2021-09-25 15:17 UTC, Markemp commented on CgfConverter/Renderers/Collada/COLLADA.cs
> +
Can you remove old unneeded code please? :)

2021-09-26 22:55 UTC, merged